#! /bin/bash
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_100/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_100/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_10/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_10/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_11/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_11/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_12/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_12/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_13/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_13/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_14/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_14/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_15/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_15/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_16/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_16/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_17/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_17/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_18/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_18/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_19/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_19/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_20/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_20/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_21/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_21/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_22/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_22/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_23/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_23/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_24/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_24/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_25/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_25/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_26/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_26/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_27/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_27/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_28/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_28/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_29/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_29/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_2/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_2/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_30/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_30/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_31/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_31/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_32/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_32/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_33/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_33/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_34/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_34/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_35/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_35/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_36/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_36/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_37/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_37/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_38/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_38/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_39/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_39/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_3/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_3/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_40/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_40/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_41/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_41/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_42/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_42/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_43/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_43/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_44/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_44/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_45/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_45/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_46/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_46/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_47/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_47/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_48/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_48/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_49/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_49/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_4/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_4/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_50/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_50/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_51/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_51/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_52/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_52/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_53/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_53/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_54/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_54/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_55/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_55/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_56/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_56/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_57/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_57/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_58/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_58/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_59/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_59/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_5/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_5/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_60/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_60/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_61/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_61/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_62/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_62/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_63/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_63/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_64/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_64/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_65/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_65/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_66/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_66/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_67/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_67/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_68/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_68/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_69/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_69/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_6/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_6/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_70/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_70/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_71/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_71/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_72/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_72/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_73/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_73/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_74/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_74/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_75/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_75/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_76/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_76/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_77/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_77/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_78/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_78/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_79/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_79/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_7/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_7/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_80/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_80/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_81/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_81/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_82/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_82/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_83/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_83/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_84/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_84/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_85/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_85/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_86/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_86/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_87/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_87/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_88/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_88/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_89/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_89/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_8/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_8/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_90/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_90/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_91/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_91/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_92/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_92/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_93/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_93/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_94/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_94/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_95/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_95/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_96/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_96/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_97/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_97/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_98/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_98/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_99/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_99/FLSNPL_NoCC_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_9/FLSNPL_2M_Ceiling/
cp ~/Dropbox/RA-FL-Shore-Birds/SensitivityAnalysis/SACode_SNPL/RunMP.bat Unif_9/FLSNPL_NoCC_Ceiling/