#! /bin/bash
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_1
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_2
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_3
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_4
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_5
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_6
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_7
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_8
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_9
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_10
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_11
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_12
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_13
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_14
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_15
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_16
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_17
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_18
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_19
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_20
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_21
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_22
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_23
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_24
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_25
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_26
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_27
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_28
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_29
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_30
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_31
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_32
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_33
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_34
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_35
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_36
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_37
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_38
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_39
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_40
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_41
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_42
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_43
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_44
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_45
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_46
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_47
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_48
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_49
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_50
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_51
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_52
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_53
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_54
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_55
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_56
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_57
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_58
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_59
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_60
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_61
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_62
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_63
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_64
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_65
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_66
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_67
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_68
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_69
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_70
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_71
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_72
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_73
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_74
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_75
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_76
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_77
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_78
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_79
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_80
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_81
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_82
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_83
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_84
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_85
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_86
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_87
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_88
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_89
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_90
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_91
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_92
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_93
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_94
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_95
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_96
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_97
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_98
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_99
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_100
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_101
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_102
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_103
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_104
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_105
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_106
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_107
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_108
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_109
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_110
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_111
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_112
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_113
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_114
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_115
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_116
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_117
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_118
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_119
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_120
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_121
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_122
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_123
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_124
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_125
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_126
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_127
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_128
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_129
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_130
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_131
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_132
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_133
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_134
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_135
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_136
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_137
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_138
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_139
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_140
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_141
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_142
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_143
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_144
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_145
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_146
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_147
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_148
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_149
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_150
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_151
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_152
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_153
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_154
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_155
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_156
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_157
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_158
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_159
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_160
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_161
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_162
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_163
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_164
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_165
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_166
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_167
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_168
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_169
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_170
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_171
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_172
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_173
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_174
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_175
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_176
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_177
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_178
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_179
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_180
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_181
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_182
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_183
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_184
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_185
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_186
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_187
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_188
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_189
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_190
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_191
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_192
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_193
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_194
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_195
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_196
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_197
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_198
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_199
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_200
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_201
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_202
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_203
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_204
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_205
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_206
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_207
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_208
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_209
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_210
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_211
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_212
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_213
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_214
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_215
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_216
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_217
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_218
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_219
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_220
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_221
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_222
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_223
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_224
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_225
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_226
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_227
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_228
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_229
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_230
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_231
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_232
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_233
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_234
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_235
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_236
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_237
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_238
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_239
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_240
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_241
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_242
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_243
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_244
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_245
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_246
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_247
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_248
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_249
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_250
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_251
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_252
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_253
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_254
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_255
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_256
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_257
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_258
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_259
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_260
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_261
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_262
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_263
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_264
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_265
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_266
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_267
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_268
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_269
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_270
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_271
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_272
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_273
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_274
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_275
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_276
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_277
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_278
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_279
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_280
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_281
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_282
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_283
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_284
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_285
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_286
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_287
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_288
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_289
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_290
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_291
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_292
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_293
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_294
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_295
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_296
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_297
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_298
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_299
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_300
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_301
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_302
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_303
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_304
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_305
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_306
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_307
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_308
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_309
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_310
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_311
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_312
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_313
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_314
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_315
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_316
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_317
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_318
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_319
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_320
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_321
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_322
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_323
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_324
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_325
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_326
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_327
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_328
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_329
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_330
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_331
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_332
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_333
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_334
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_335
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_336
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_337
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_338
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_339
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_340
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_341
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_342
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_343
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_344
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_345
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_346
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_347
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_348
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_349
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_350
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_351
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_352
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_353
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_354
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_355
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_356
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_357
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_358
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_359
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_360
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_361
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_362
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_363
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_364
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_365
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_366
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_367
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_368
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_369
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_370
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_371
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_372
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_373
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_374
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_375
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_376
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_377
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_378
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_379
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_380
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_381
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_382
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_383
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_384
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_385
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_386
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_387
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_388
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_389
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_390
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_391
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_392
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_393
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_394
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_395
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_396
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_397
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_398
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_399
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_400
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_401
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_402
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_403
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_404
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_405
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_406
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_407
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_408
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_409
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_410
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_411
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_412
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_413
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_414
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_415
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_416
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_417
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_418
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_419
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_420
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_421
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_422
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_423
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_424
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_425
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_426
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_427
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_428
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_429
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_430
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_431
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_432
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_433
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_434
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_435
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_436
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_437
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_438
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_439
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_440
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_441
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_442
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_443
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_444
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_445
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_446
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_447
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_448
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_449
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_450
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_451
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_452
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_453
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_454
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_455
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_456
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_457
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_458
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_459
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_460
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_461
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_462
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_463
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_464
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_465
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_466
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_467
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_468
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_469
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_470
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_471
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_472
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_473
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_474
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_475
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_476
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_477
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_478
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_479
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_480
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_481
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_482
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_483
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_484
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_485
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_486
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_487
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_488
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_489
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_490
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_491
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_492
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_493
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_494
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_495
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_496
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_497
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_498
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_499
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_500
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_501
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_502
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_503
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_504
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_505
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_506
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_507
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_508
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_509
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_510
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_511
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_512
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_513
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_514
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_515
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_516
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_517
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_518
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_519
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_520
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_521
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_522
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_523
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_524
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_525
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_526
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_527
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_528
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_529
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_530
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_531
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_532
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_533
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_534
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_535
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_536
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_537
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_538
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_539
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_540
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_541
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_542
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_543
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_544
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_545
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_546
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_547
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_548
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_549
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_550
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_551
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_552
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_553
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_554
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_555
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_556
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_557
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_558
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_559
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_560
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_561
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_562
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_563
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_564
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_565
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_566
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_567
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_568
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_569
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_570
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_571
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_572
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_573
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_574
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_575
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_576
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_577
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_578
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_579
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_580
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_581
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_582
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_583
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_584
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_585
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_586
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_587
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_588
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_589
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_590
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_591
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_592
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_593
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_594
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_595
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_596
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_597
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_598
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_599
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_600
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_601
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_602
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_603
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_604
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_605
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_606
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_607
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_608
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_609
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_610
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_611
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_612
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_613
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_614
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_615
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_616
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_617
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_618
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_619
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_620
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_621
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_622
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_623
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_624
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_625
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_626
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_627
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_628
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_629
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_630
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_631
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_632
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_633
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_634
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_635
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_636
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_637
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_638
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_639
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_640
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_641
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_642
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_643
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_644
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_645
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_646
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_647
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_648
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_649
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_650
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_651
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_652
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_653
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_654
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_655
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_656
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_657
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_658
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_659
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_660
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_661
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_662
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_663
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_664
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_665
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_666
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_667
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_668
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_669
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_670
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_671
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_672
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_673
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_674
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_675
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_676
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_677
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_678
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_679
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_680
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_681
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_682
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_683
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_684
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_685
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_686
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_687
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_688
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_689
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_690
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_691
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_692
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_693
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_694
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_695
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_696
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_697
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_698
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_699
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_700
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_701
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_702
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_703
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_704
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_705
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_706
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_707
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_708
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_709
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_710
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_711
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_712
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_713
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_714
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_715
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_716
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_717
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_718
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_719
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_720
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_721
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_722
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_723
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_724
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_725
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_726
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_727
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_728
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_729
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_730
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_731
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_732
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_733
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_734
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_735
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_736
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_737
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_738
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_739
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_740
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_741
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_742
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_743
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_744
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_745
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_746
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_747
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_748
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_749
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_750
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_751
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_752
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_753
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_754
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_755
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_756
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_757
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_758
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_759
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_760
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_761
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_762
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_763
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_764
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_765
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_766
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_767
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_768
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_769
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_770
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_771
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_772
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_773
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_774
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_775
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_776
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_777
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_778
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_779
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_780
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_781
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_782
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_783
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_784
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_785
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_786
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_787
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_788
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_789
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_790
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_791
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_792
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_793
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_794
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_795
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_796
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_797
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_798
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_799
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_800
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_801
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_802
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_803
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_804
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_805
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_806
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_807
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_808
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_809
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_810
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_811
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_812
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_813
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_814
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_815
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_816
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_817
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_818
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_819
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_820
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_821
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_822
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_823
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_824
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_825
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_826
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_827
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_828
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_829
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_830
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_831
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_832
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_833
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_834
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_835
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_836
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_837
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_838
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_839
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_840
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_841
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_842
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_843
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_844
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_845
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_846
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_847
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_848
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_849
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_850
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_851
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_852
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_853
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_854
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_855
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_856
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_857
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_858
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_859
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_860
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_861
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_862
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_863
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_864
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_865
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_866
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_867
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_868
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_869
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_870
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_871
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_872
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_873
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_874
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_875
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_876
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_877
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_878
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_879
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_880
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_881
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_882
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_883
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_884
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_885
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_886
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_887
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_888
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_889
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_890
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_891
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_892
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_893
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_894
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_895
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_896
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_897
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_898
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_899
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_900
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_901
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_902
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_903
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_904
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_905
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_906
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_907
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_908
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_909
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_910
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_911
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_912
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_913
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_914
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_915
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_916
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_917
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_918
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_919
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_920
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_921
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_922
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_923
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_924
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_925
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_926
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_927
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_928
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_929
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_930
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_931
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_932
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_933
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_934
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_935
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_936
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_937
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_938
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_939
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_940
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_941
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_942
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_943
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_944
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_945
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_946
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_947
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_948
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_949
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_950
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_951
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_952
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_953
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_954
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_955
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_956
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_957
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_958
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_959
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_960
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_961
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_962
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_963
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_964
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_965
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_966
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_967
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_968
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_969
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_970
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_971
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_972
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_973
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_974
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_975
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_976
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_977
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_978
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_979
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_980
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_981
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_982
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_983
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_984
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_985
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_986
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_987
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_988
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_989
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_990
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_991
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_992
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_993
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_994
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_995
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_996
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_997
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_998
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_999
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_10_Unif Unif_1000