#! /bin/bash
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_1
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_2
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_3
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_4
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_5
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_6
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_7
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_8
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_9
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_10
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_11
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_12
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_13
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_14
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_15
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_16
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_17
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_18
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_19
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_500_Unif Unif_20