#! /bin/bash
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_1
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_2
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_3
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_4
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_5
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_6
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_7
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_8
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_9
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_10
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_11
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_12
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_13
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_14
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_15
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_16
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_17
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_18
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_19
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_20
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_21
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_22
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_23
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_24
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_25
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_26
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_27
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_28
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_29
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_30
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_31
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_32
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_33
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_34
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_35
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_36
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_37
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_38
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_39
cp -r /home/mlammens/Projects/SnowyPlover/Templates/SampleSize_250_LHS LHS_40