#! /bin/bash
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_10/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_10/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_11/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_11/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_12/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_12/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_13/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_13/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_14/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_14/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_15/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_15/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_16/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_16/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_17/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_17/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_18/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_18/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_19/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_19/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_1/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_1/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_20/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_20/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_2/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_2/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_3/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_3/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_4/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_4/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_5/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_5/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_6/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_6/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_7/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_7/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_8/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_8/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_9/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_9/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_10/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_10/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_11/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_11/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_12/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_12/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_13/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_13/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_14/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_14/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_15/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_15/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_16/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_16/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_17/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_17/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_18/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_18/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_19/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_19/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_1/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_1/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_20/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_20/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_2/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_2/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_3/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_3/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_4/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_4/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_5/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_5/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_6/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_6/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_7/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_7/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_8/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_8/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_9/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_500_Rep/Unif_9/FLSNPL_2M_Ceiling/