cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_100/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_100/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_11/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_11/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_12/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_12/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_13/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_13/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_14/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_14/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_15/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_15/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_16/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_16/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_17/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_17/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_18/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_18/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_19/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_19/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_20/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_20/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_21/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_21/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_22/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_22/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_23/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_23/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_24/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_24/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_25/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_25/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_26/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_26/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_27/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_27/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_28/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_28/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_29/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_29/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_30/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_30/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_31/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_31/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_32/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_32/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_33/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_33/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_34/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_34/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_35/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_35/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_36/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_36/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_37/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_37/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_38/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_38/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_39/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_39/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_40/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_40/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_41/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_41/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_42/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_42/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_43/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_43/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_44/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_44/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_45/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_45/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_46/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_46/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_47/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_47/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_48/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_48/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_49/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_49/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_50/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_50/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_51/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_51/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_52/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_52/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_53/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_53/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_54/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_54/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_55/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_55/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_56/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_56/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_57/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_57/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_58/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_58/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_59/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_59/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_60/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_60/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_61/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_61/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_62/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_62/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_63/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_63/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_64/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_64/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_65/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_65/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_66/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_66/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_67/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_67/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_68/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_68/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_69/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_69/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_70/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_70/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_71/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_71/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_72/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_72/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_73/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_73/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_74/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_74/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_75/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_75/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_76/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_76/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_77/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_77/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_78/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_78/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_79/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_79/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_80/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_80/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_81/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_81/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_82/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_82/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_83/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_83/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_84/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_84/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_85/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_85/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_86/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_86/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_87/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_87/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_88/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_88/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_89/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_89/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_90/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_90/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_91/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_91/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_92/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_92/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_93/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_93/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_94/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_94/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_95/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_95/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_96/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_96/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_97/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_97/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_98/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_98/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_99/FLSNPL_NoCC_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_99/FLSNPL_NoCC_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_100/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_100/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_11/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_11/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_12/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_12/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_13/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_13/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_14/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_14/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_15/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_15/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_16/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_16/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_17/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_17/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_18/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_18/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_19/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_19/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_20/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_20/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_21/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_21/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_22/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_22/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_23/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_23/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_24/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_24/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_25/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_25/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_26/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_26/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_27/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_27/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_28/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_28/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_29/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_29/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_30/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_30/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_31/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_31/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_32/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_32/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_33/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_33/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_34/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_34/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_35/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_35/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_36/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_36/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_37/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_37/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_38/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_38/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_39/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_39/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_40/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_40/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_41/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_41/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_42/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_42/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_43/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_43/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_44/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_44/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_45/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_45/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_46/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_46/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_47/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_47/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_48/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_48/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_49/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_49/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_50/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_50/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_51/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_51/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_52/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_52/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_53/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_53/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_54/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_54/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_55/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_55/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_56/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_56/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_57/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_57/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_58/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_58/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_59/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_59/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_60/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_60/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_61/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_61/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_62/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_62/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_63/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_63/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_64/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_64/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_65/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_65/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_66/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_66/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_67/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_67/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_68/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_68/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_69/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_69/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_70/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_70/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_71/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_71/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_72/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_72/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_73/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_73/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_74/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_74/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_75/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_75/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_76/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_76/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_77/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_77/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_78/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_78/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_79/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_79/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_80/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_80/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_81/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_81/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_82/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_82/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_83/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_83/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_84/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_84/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_85/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_85/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_86/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_86/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_87/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_87/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_88/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_88/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_89/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_89/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_90/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_90/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_91/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_91/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_92/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_92/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_93/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_93/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_94/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_94/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_95/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_95/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_96/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_96/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_97/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_97/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_98/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_98/FLSNPL_2M_Ceiling/
cp /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_99/FLSNPL_2M_Ceiling/snpl_out/* /home/mlammens/Projects/SnowyPlover/SampleSize_100_Rep/LHS_99/FLSNPL_2M_Ceiling/
