#!/bin/bash
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_10/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_10/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_11/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_11/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_12/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_12/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_13/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_13/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_14/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_14/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_15/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_15/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_16/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_16/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_17/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_17/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_18/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_18/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_19/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_19/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_1/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_1/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_20/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_20/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_21/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_21/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_22/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_22/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_23/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_23/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_24/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_24/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_25/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_25/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_26/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_26/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_27/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_27/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_28/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_28/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_29/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_29/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_2/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_2/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_30/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_30/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_31/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_31/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_32/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_32/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_33/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_33/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_34/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_34/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_35/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_35/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_36/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_36/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_37/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_37/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_38/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_38/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_39/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_39/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_3/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_3/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_40/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_40/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_4/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_4/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_5/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_5/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_6/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_6/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_7/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_7/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_8/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_8/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_9/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/LHS_9/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_10/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_10/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_11/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_11/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_12/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_12/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_13/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_13/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_14/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_14/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_15/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_15/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_16/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_16/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_17/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_17/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_18/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_18/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_19/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_19/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_1/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_1/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_20/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_20/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_21/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_21/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_22/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_22/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_23/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_23/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_24/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_24/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_25/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_25/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_26/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_26/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_27/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_27/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_28/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_28/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_29/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_29/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_2/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_2/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_30/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_30/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_31/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_31/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_32/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_32/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_33/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_33/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_34/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_34/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_35/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_35/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_36/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_36/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_37/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_37/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_38/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_38/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_39/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_39/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_3/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_3/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_40/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_40/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_4/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_4/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_5/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_5/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_6/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_6/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_7/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_7/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_8/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_8/FLSNPL_NoCC_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_9/FLSNPL_2M_Ceiling/snpl_list.txt
mp_nix2win.sh /home/mlammens/Projects/SnowyPlover/SampleSize_250_Rep/Unif_9/FLSNPL_NoCC_Ceiling/snpl_list.txt